name: weixin
on:
  workflow_dispatch:
  schedule: 
    # 国际标准时间，北京时间需要+8小时
    # 分别代表 分钟、小时、日期、月份、星期几，没有用*代替。
    # 现在是国际时间的0点01分，也就是北京时间的早上8点01
    - cron: '01 00 * * *'

env:
# 把时区设置为了北京时间，可以规避因为时区问题造成的日期不准确现象
  TZ: 'Asia/Shanghai'
  
jobs:
#将工作流程中运行的所有作业组合在一起
  build:
  #定义名为 build 的作业。 子键将定义作业的属性 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
    
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
            python-version: '3.x'
#           python-version: 3.9.1
      - name: install pip packages
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: weixin
        run: |
          python3 main.py
